### ISSUE TITLE
(Question) What is the license for this package?

### ISSUE THREAD

**Issue by soimkim** [vsviridov/mootools-node#11]
What is the license for this package?
It is written MIT-style, but there is no License text. How about adding a **LICENSE** file with license text?
And how about adding license to package.json?
ex- `"license": "MIT-style",`

**Comment by vsviridov** [comment]
Should probably mention that you should not be using this in this day and age... 🤣

**Comment by soimkim** [comment]
@vsviridov , Why not use this?
I actually came across this package while checking that security vulnerabilities were found.
- https://snyk.io/vuln/SNYK-JS-MOOTOOLS-1325536

**Comment by vsviridov** [comment]
Basically it hasn't been updated in over 6 years, a lot of the functionality is part of modern JavaScript these days. And there are better libraries to cover some functionality that remains. Also, it messes with built-ins. And the vulnerabilities...

**Comment by soimkim** [comment]
Thanks for letting me know. 👍

**Comment by rwhogg** [comment]
I'm the one who reported that vulnerability to Snyk, feel free to send me an email about it if you want to @vsviridov
